export const SKILL_TYPES = ["SERVE","RECEIVE","SET","ATTACK","BLOCK","DIG","FREEBALL"] as const;
export const OUTCOME = ["PLUS","ZERO","MINUS"] as const;

export const SERVE_TYPES = ["FLOAT","JUMP_FLOAT","JUMP_SPIN","UNDERHAND","HYBRID"];
export const SERVE_OUTCOME_DETAIL = ["ACE","IN_PERFECT_PRESSURE","IN_MODERATE_PRESSURE","IN_EASY","NET","OUT_LONG","OUT_WIDE","FOOT_FAULT","ROTATION_FAULT"];
export const SERVE_TACTICAL_INTENTION = ["TARGET_WEAK_PASSER","TARGET_LIBERO","SHORT_SERVE","DEEP_SERVE","ZONE_DISRUPTION","NONE"];

export const RECEIVE_TYPES = ["FOREARM","OVERHEAD","EMERGENCY"];
export const RECEIVE_RATING_DETAIL = ["3_PERFECT","2_POSITIVE","1_OFF_SYSTEM","0_ERROR"];
export const RECEIVE_ERROR_TYPES = ["PLATFORM_ANGLE","FOOTWORK","COMMUNICATION","LATE_REACTION","BALL_MISJUDGMENT","TECHNICAL_BREAKDOWN"];

export const SET_TYPES = ["HIGH_OUTSIDE","QUICK_1","QUICK_2","QUICK_3","BACK_SET","SLIDE","PIPE","DUMP"];
export const SET_QUALITY_DETAIL = ["PERFECT","SLIGHTLY_OFF","POOR","ERROR"];
export const SET_ERROR_TYPES = ["DOUBLE_TOUCH","LIFT","MISCOMMUNICATION","WRONG_DECISION","FOOTWORK","TIMING","SET_OUT_OF_SYSTEM","SET_OUT","NET_TOUCH"];

export const ATTACK_TYPES = ["POWER","ROLL","TIP","TOOL_BLOCK","LINE","CROSS","SEAM"];
export const ATTACK_OUTCOME_DETAIL = ["KILL","BLOCKED","DUG","OUT","NET","TOOL_BLOCK","BLOCK_OUT"];
export const ATTACK_ERROR_TYPES = ["TECHNICAL_SWING","POOR_APPROACH","BAD_DECISION","FORCED_BY_BAD_SET","FATIGUE","TIMING"];

export const BLOCK_TYPES = ["SOLO","ASSIST","TOUCH","LATE_BLOCK"];
export const BLOCK_OUTCOME_DETAIL = ["STUFF","TOUCH","ERROR","NONE","BLOCK_OUT"];
export const BLOCK_ERROR_TYPES = ["NET","LATE_READ","HAND_POSITION","JUMP_TIMING","CLOSED_WRONG_ANGLE","NET_TOUCH","OVERREACH","BLOCK_OUT"];

export const DIG_TYPES = ["CONTROLLED","EMERGENCY","PANCAKE","ONE_ARM"];
export const DIG_OUTCOME_DETAIL = ["CONTROLLED","NOT_CONTROLLED","ERROR","NONE"];
export const DIG_ERROR_TYPES = ["POOR_READING","SLOW_REACTION","POSITIONING","COMMUNICATION"];

export const ERROR_CATEGORY = ["NONE","TECHNICAL","DECISION","PRESSURE","FATIGUE"];

export const TECHNICAL_ERRORS = ["FOOTWORK","PLATFORM_ANGLE","ARM_SWING","JUMP_TIMING","HAND_POSITION","CONTACT_POINT"];
export const DECISION_ERRORS = ["WRONG_TARGET","POOR_SHOT_SELECTION","MISREAD_BLOCK","PREDICTABLE_PLAY","COMMUNICATION_FAILURE"];
export const PRESSURE_ERRORS = ["END_OF_SET","AFTER_TIMEOUT","SERVICE_PRESSURE","MOMENTUM_SHIFT"];
export const FATIGUE_ERRORS = ["LATE_SET_DROP","POOR_RECOVERY","SLOW_REACTION"];

export const ZONES = ["1","2","3","4","5","6","DEEP_1","DEEP_5","SHORT_2","SHORT_4","SEAM_56","SEAM_12"];

export const ALL_ENUMS = {
  SKILL_TYPES, OUTCOME, ZONES,
  SERVE_TYPES, SERVE_OUTCOME_DETAIL, SERVE_TACTICAL_INTENTION,
  RECEIVE_TYPES, RECEIVE_RATING_DETAIL, RECEIVE_ERROR_TYPES,
  SET_TYPES, SET_QUALITY_DETAIL, SET_ERROR_TYPES,
  ATTACK_TYPES, ATTACK_OUTCOME_DETAIL, ATTACK_ERROR_TYPES,
  BLOCK_TYPES, BLOCK_OUTCOME_DETAIL, BLOCK_ERROR_TYPES,
  DIG_TYPES, DIG_OUTCOME_DETAIL, DIG_ERROR_TYPES,
  ERROR_CATEGORY, TECHNICAL_ERRORS, DECISION_ERRORS, PRESSURE_ERRORS, FATIGUE_ERRORS,
};
